name: Node Continuous Integration
on:
  push:
    branches: ['development']
  pull_request:
    branches: ['development']
jobs:
  acceptance_test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: recruitment_application
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - run: tree
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      - name: Checkout the Backend
        uses: actions/checkout@v3
        with:
          repository: IV1201-Group12/IV1201-backend
          ref: development
          path: backend
      - name: Checkout the Frontend
        uses: actions/checkout@v3
        with:
          path: frontend
      - run: pwd && tree
      - name: Install Backend Dependencies
        run: npm --prefix backend/ ci
      - name: Start Backend
        run: npm --prefix backend/ run start&
        env:
          DATABASE_HOST: localhost
          DATABASE_PORT: 5432
          DATABASE_USERNAME: postgres
          DATABASE_PASSWORD: postgres
          DATABASE_NAME: recruitment_application
          DATABASE_DIALECT: postgres
      - name: Install Frontend Dependencies
        run: npm --prefix frontend/ ci
      # - name: Install Playwright Browsers
      #   run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: cd frontend/ && npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 30
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/ms-playwright
